### PR TITLE
Small modifications to a few sagan rules

### PR DESCRIPTION
**Pull request by rtkkdeng**
Small modifications to two sagan rules. 
 * The first one changes the classification type of "SSH traffic detected at suspicious time" from "trojan-activity" to "suspicious-traffic". This classification seemed to make more sense.
 * The second one adds a normalize rule for "TCP access denied by ACL" rules. Originally, the rule failed to parse the ports correctly using parse_port, so I added normalize to extract the ports instead.

### CODE REVIEW

**Comment by rtkrruvinskiy** [comment]
@beave Would you consider merging either of the changes here?

**Comment by beave** [comment]
Looks great and thank you!  

Consider bumping the "rev" next time.   

It's merged!

**Comment by rtkrruvinskiy** [comment]
@beave Thanks for looking at the PR, and thanks for the point regarding `rev`! Will do.

The commit in this PR changes the rule classification for "SSH traffic detected at suspicious time" in fortinet-aetas.rules, but I noticed that the change that was made in the repo was to fortinet-geoip.rules. I was just wondering if there was a reason for that. Thanks!

**Comment by beave** [comment]
I must have screwed up (?).  I thought i merged this already.   I manually modified the rules.  Not sure what I did wrong.

**Comment by rtkrruvinskiy** [comment]
Thanks!

**Pull request closed without merging**
